Aspect is added to detections in interface, but tracking fails at finalization with "fish_manager.py", line 955, in setPathVariables     self.aspect = float(np.mean(valid_dets.aspect)) AttributeError: 'list' object has no attribute 'aspect' "